import { PricePlans } from "@/lib/submission";
import type { PriceConfig } from "@/types";

export const priceConfig: PriceConfig = {
  plans: [
    {
      title: "Free",
      description: "For Beginners",
      benefits: [
        // "Get 3 dofollow links to boost your SEO",
        // "Permanent link with backlink maintenance",
        // "Reviewed and listed within 72 hours",
        // "Publish your product the day you want",
        "Basic listing in the directory",
        "1 dofollow link to boost SEO",
        "Manual review process (3-5 business days)",
        "Limited visibility (no spotlight, side menu, or sidebar placement)",
        "Premium customer support",
      ],
      // limitations: ["Backlink to our site is required", "No customer support"],
      limitations: [],

      price: 0,
      priceSuffix: "/ mo",
      stripePriceId: null,
    },
    {
      title: "Featured",
      proTitle: "pro",
      description: "For Pro Users",
      isPopular: true,
      badgeStyle:
        "bg-linear-to-br/increasing absolute inset-x-0 -top-3 mx-auto flex h-6 w-fit items-center rounded-full from-purple-400 to-amber-300 px-3 py-1 text-xs font-medium text-amber-950 ring-1 ring-inset ring-white/20 ring-offset-1 ring-offset-gray-950/5",
      benefits: [
        // "Get >= 3 dofollow links to boost your SEO",
        // "List right now, publish whenever you want",
        // "Permanent link, no backlink required",
        // "Featured placement at the top of listings",
        // "Share through social media and newsletters",
        // "Premium customer support",
        "Get >= 3 dofollow links to boost your SEO",
        "List right now, publish whenever you want",
        "Permanent link, no backlink required",
        "Featured placement at the top of listings With Shine Border for visibility.",
        "Prominent sidebar placement",
        "Premium customer support",
      ],
      limitations: [],
      price: 19,
      priceSuffix: "/ wk",
      stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRO_PRICE_ID,
    },
    {
      title: "Sponsored",
      sponsorTitle: "sponsor",
      description: "For Sponsors",
      benefits: [
        // "Everything in Pro plan",
        // "Promote your product on almost every page",
        // "Available for all kinds of product",
        // "Only one advertisement per period",
        // "Schedule your advertising period",
        // "Premium customer support",
        "Everything in Pro plan",
        "Promote your product on almost every page",
        "Exclusive one advertisement per period for maximum exposure",
        "Only one advertisement per period",
        "Schedule your advertising period",
        "Premium customer support",
      ],
      limitations: [],
      price: 29,
      priceSuffix: "/ wk",
      stripePriceId: process.env.NEXT_PUBLIC_STRIPE_SPONSOR_PRICE_ID,
    },
  ],
};
